---
- name: Copy inpex.html file to webserver
  hosts: webservers
  become: yes
  tasks:
    - name: copy index.html
      copy:
        src: /mnt/e/Task_01/backup_01/app.txt
        dest: /mnt/e/Task_01/backup_02/app.txt
        mode: "0644"
