---
- name: Deploy web application
  hosts: webservers
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name: apache2
        state: present

    - name: Copy application files
      copy:
        src: /mnt/e/Task_01/backup_01
        dest: /mnt/e/Task_01/backup_02
        mode: '0755'

    - name: Start and enable application
      service:
        name: apache2
        state: started
        enabled: yes
