---
- name: Remove Apache web server
  hosts: webservers
  become: yes
  tasks:
    - name: Stop Apache service
      service:
        name: apache2
        state: stopped
      ignore_errors: yes

    - name: Disable Apache service
      service:
        name: apache2
        enabled: no
      ignore_errors: yes

    - name: Remove Apache package
      apt:
        name: apache2
        state: absent
      ignore_errors: yes

    - name: Clean up leftover Apache configuration files
      file:
        path: /etc/apache2
        state: absent
      ignore_errors: yes
